Using tensorflow basic functions instead of tf.nn...
Under my env (python 3.5, tensorflow1.2) the  code of tf.nn.dynamic_rnn cause error.
outputs, state = tf.nn.dynamic_rnn(cell, x_one_hot, initial_state=self.initial_state)
Error message:
ValueError: Trying to share variable rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel, but specified shape (256, 512) and found shape (211, 512).

Using tensorflow basic functions to do this exercies. Look at https://github.com/xaibeing/Udacity-Deep-Learning/blob/master/README.md